### ISSUE TITLE
Kotlin 

### ISSUE THREAD

**Issue by hamza94max** [iFr0z/TimePickerCompact#2]
where are time_p.hour in code ??

val customTime = "${time_p.hour}:${time_p.minute}" // set/get hour and minute with support all API
output_time_tv.text = customTime

**Comment by iFr0z** [comment]
> where are time_p.hour in code ??
> 
> 
> 
> 
> 
> val customTime = "${time_p.hour}:${time_p.minute}" // set/get hour and minute with support all API
> 
> output_time_tv.text = customTime

Sample -> xml -> layout 

```
<ru.ifr0z.timepickercompact.TimePickerCompact
        android:id="@+id/time_p"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:timePickerMode="spinner" />
```
